version: '3'

services:
  simple-discord-tts:
    build: .
    volumes:
      - ./:/usr/local/src/simple-discord-tts
    restart: always

  voice-backend:
    image: alcnaka/openjtalk-rest-api:latest
    restart: always
