select = ["ALL"]

# Never enforce `E501` (line length violations).
ignore = ["D100", "D101", "D102", "D103", "D104", "D107"]

[extend-per-file-ignores]
"tests/*" = [
    "S101",   # assert
    "ANN101", # missing-type-self
    "ANN201", # missing-return-type-undocumented-public-function
]
