select = ["ALL"]

# Never enforce `E501` (line length violations).
ignore = ["D100", "D101", "D102", "D103", "D104", "D107"]

# Avoid trying to fix flake8-bugbear (`B`) violations.
# unfixable = ["B"]

# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
# [per-file-ignores]
# "__init__.py" = ["E402"]
